### ISSUE TITLE
Clean up `flake.nix`

### ISSUE THREAD

**Issue by airone01** [airone01/dotfiles2#10]
## TODO
- [x] Goal is setting up VM images as well as nixos systems in the same flake.nix
      ~~I got it working once, then at c5eb34a479ddbc3693e2b640a97a960663870c77 I got error (see below~~)
      Edit at 968a5de8bb35a8e06fc415ddcf7076158cc1cfe8: it was because I hadn't yet figured out that `nixosConfigurations` doesn't take a `system` attr. I feel stupid.
- [x] Write functions to make my life easier
- [x] Simplify + clarify the code
